AWSTemplateFormatVersion: '2010-09-09'
Description: Repositorios públicos ECR para backend y frontend

Resources:
  BackendPublicEcr:
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: casv/funds-api

Outputs:
  BackendRepositoryUri:
    Description: URI del repositorio público de backend
    Value: !GetAtt BackendPublicEcr.RepositoryUri
