AWSTemplateFormatVersion: '2010-09-09'
Description: Repositorio público ECR para backend

Parameters:
  RepositoryUri:
    Type: String
    Default: public.ecr.aws/a6t3n9v6/casv/funds-api
    Description: URI del repositorio público (manual)

Resources:
  BackendPublicEcr:
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: casv/funds-api

Outputs:
  BackendRepositoryUri:
    Description: URI del repositorio público de backend
    Value: !Ref RepositoryUri
