name: Deploy - funds-api

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Crear repositorios ECR públicos (si no existen)
        run: |
          aws cloudformation deploy \
            --template-file ecr-repo.yaml \
            --stack-name funds-api-repo \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Obtener URI del repositorio público ECR
        id: ecr-uri
        run: |
          URI=$(aws ecr-public describe-repositories \
            --query "repositories[?repositoryName=='casv/funds-api'].repositoryUri" \
            --output text)
          echo "repository_uri=$URI" >> $GITHUB_OUTPUT

      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build Docker image
        run: docker build -t funds-api .

      - name: Tag Docker image
        run: docker tag funds-api:latest ${{ steps.ecr-uri.outputs.repository_uri }}:latest

      - name: Push Docker image
        run: docker push ${{ steps.ecr-uri.outputs.repository_uri }}:latest

      - name: Deploy infraestructura ECS con CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file backend-infra.yaml \
            --stack-name funds-api-infra \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides ImageUri=${{ steps.ecr-uri.outputs.repository_uri }}:latest
