name: Deploy - funds-api

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: ECR para backend
        run: |
          aws cloudformation deploy \
            --template-file ecr-repo.yaml \
            --stack-name funds-api-repo \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build Docker image
        run: docker build -t funds-api .

      - name: Tag Docker image
        run: docker tag funds-api:latest public.ecr.aws/a6t3n9v6/casv/funds-api:latest

      - name: Push Docker image
        run: docker push public.ecr.aws/a6t3n9v6/casv/funds-api:latest

      - name: ECS Deploy
        run: |
          aws cloudformation deploy \
            --template-file backend-infra.yaml \
            --stack-name funds-api-infra \
            --capabilities CAPABILITY_NAMED_IAM
