name: Build and Deploy Backend to AWS

on:
  push:
    branches: [ main ]

jobs:
  build-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build Docker image
        run: docker build -t funds-api .

      - name: Tag Docker image
        run: docker tag funds-api:latest public.ecr.aws/h7b2e7k1/casv/funds-api:latest

      - name: Push Docker image to Amazon ECR Public
        run: docker push public.ecr.aws/h7b2e7k1/casv/funds-api:latest

      - name: Deploy CloudFormation (Backend Infra)
        run: |
          aws cloudformation deploy \
            --stack-name funds-backend-stack \
            --template-file cloudformation-backend.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides ImageUri=public.ecr.aws/h7b2e7k1/casv/funds-api:latest
